/** Conteúdo da apresentação: Proposta de Atuação iCEV. */

export const DECK_META = {
  title: "Proposta de Atuação: Coordenador de Marketing",
  shortTitle: "Proposta de Atuação iCEV",
  subtitle: "iCEV | Use as setas para navegar, G para a grade",
  institutionFooter: "Instituto de Ensino Superior | iCEV: Teresina/PI",
  deckFooter: "iCEV | Proposta de Atuação: Coordenador de Marketing",
} as const;
export interface CoverContent { badge: string; title: string; subtitle: string; lines: string[]; }
export interface SummaryItem { number: string; label: string; }
export interface ColumnContent { heading: string; items: string[]; }
export interface MonthContent { kicker: string; title: string; activeTab: number; pillars: string[]; leftItems: string[]; rightItems: string[]; deliverableLabel: string; deliverable: string; }
export interface BadgeCard { badge: string; body: string; meta: string; }
export interface JourneyStep { number: string; title: string; body: string; }
export interface KpiRow { indicator: string; target: string; frequency: string; }
export interface NumberedCard { number: string; title: string; }

export const SLIDE_01: CoverContent = { badge: "PRIMEIROS 3 MESES", title: "Proposta de Atuação", subtitle: "Coordenador de Marketing", lines: ["Instituto de Ensino Superior | iCEV", "Antonio Fontes", "comfontes@gmail.com", "(86) 99997 4164"] };
export const SLIDE_02 = { kicker: "VISÃO EXECUTIVA", title: "O que esta proposta entrega", items: [{ number: "01", label: "Diagnóstico: entender funil, canais, dados, equipe e gargalos" }, { number: "02", label: "Captação: gerar demanda qualificada e aumentar conversão" }, { number: "03", label: "Jornada: reduzir atritos do primeiro contato à matrícula" }, { number: "04", label: "Pessoas: fortalecer comunicação, colaboração e pertencimento" }, { number: "05", label: "Gestão: acompanhar KPIs e decidir com base em evidências" }, { number: "06", label: "90 dias: diagnosticar, implementar, medir e escalar" }] satisfies SummaryItem[] };
export const SLIDE_03 = { kicker: "LEITURA DO DESAFIO", title: "Dois objetivos, uma mesma lógica de gestão", left: { heading: "01 | Captação e matrícula", items: ["Construir um funil por oferta: atração, lead, oportunidade, inscrição e matrícula.", "Combinar mídia paga, conteúdo, redes sociais, eventos, landing pages e WhatsApp.", "Segmentar mensagens por público e estágio de decisão do candidato.", "Transformar diferenciais acadêmicos em argumentos de escolha e prova social.", "Integrar Marketing e Comercial para responder rápido e recuperar oportunidades."] } satisfies ColumnContent, right: { heading: "02 | Clima e colaboração", items: ["Criar rituais de alinhamento, prioridades claras e responsabilidades visíveis.", "Promover brainstorms, troca de aprendizados e construção conjunta de campanhas.", "Reconhecer entregas, evolução e iniciativas que gerem impacto.", "Conectar Marketing, Comercial, Coordenações e demais áreas à jornada do aluno.", "Dar espaço para experimentação, testes e inovação com acompanhamento de resultado."] } satisfies ColumnContent };
export const SLIDE_04 = { kicker: "1º MÊS | DIAGNÓSTICO", title: "Antes de acelerar, descobrir onde está o ganho", left: { heading: "Dados que eu buscaria", items: ["Leads, inscrições e matrículas por curso, período e origem.", "Conversão entre etapas e tempo médio até atendimento e matrícula.", "CPL, CAC, investimento, retorno e qualidade dos leads por canal.", "Desempenho de campanhas, landing pages, redes sociais e conteúdos.", "Taxas de abandono, motivos de perda e oportunidades de recuperação."] } satisfies ColumnContent, right: { heading: "Perguntas que eu responderia", items: ["Quais ofertas têm maior potencial e quais gargalos precisam de atenção primeiro?", "Que argumentos realmente diferenciam o iCEV para cada público?", "Onde o candidato abandona e por quê?", "Marketing entrega lead qualificado? Comercial responde no tempo certo?", "Quais ações já funcionam e merecem mais investimento?"] } satisfies ColumnContent };
export const MONTH_TABS = ["1º mês", "2º mês", "3º mês"] as const;
export const SLIDE_05: MonthContent = { kicker: "PLANO DOS 3 PRIMEIROS MESES", title: "1º mês: Diagnóstico e planejamento", activeTab: 0, pillars: ["Diagnosticar", "Alinhar", "Priorizar"], leftItems: ["Auditar funil, canais, campanhas, conteúdo, CRM e jornada do candidato.", "Entrevistar Marketing, Comercial, Coordenações e lideranças.", "Mapear gargalos, quick wins e oportunidades por oferta."], rightItems: ["Definir baseline e painel inicial de KPIs.", "Escolher 3 a 5 prioridades para o trimestre, evitando dispersão.", "Criar calendário de campanhas e rotina de alinhamento entre áreas."], deliverableLabel: "ENTREGA DO MÊS", deliverable: "Diagnóstico 360 graus, prioridades e plano tático de 90 dias" };
export const SLIDE_06: MonthContent = { kicker: "PLANO DOS 3 PRIMEIROS MESES", title: "2º mês: Implementação", activeTab: 1, pillars: ["Executar", "Testar", "Acompanhar"], leftItems: ["Lançar campanhas prioritárias por oferta, público e etapa do funil.", "Criar conteúdos de prova social, carreira, rotina acadêmica e diferenciais.", "Ativar landing pages, remarketing, WhatsApp e fluxos de nutrição."], rightItems: ["Definir responsáveis, prazos e critérios de aprovação.", "Implantar reunião semanal Marketing e Comercial baseada no funil.", "Testar criativos, ofertas, públicos, CTAs e abordagens de atendimento."], deliverableLabel: "ENTREGA DO MÊS", deliverable: "Campanhas no ar, rotina comercial e primeiros testes comparativos" };
export const SLIDE_07: MonthContent = { kicker: "PLANO DOS 3 PRIMEIROS MESES", title: "3º mês: Otimização e resultados", activeTab: 2, pillars: ["Medir", "Otimizar", "Escalar"], leftItems: ["Comparar resultados com o baseline e localizar os maiores ganhos e gargalos.", "Analisar performance por escola ou curso, canal, campanha e etapa do funil.", "Cortar desperdícios e reforçar ações com melhor conversão e qualidade de lead."], rightItems: ["Realocar verba e esforço para canais e mensagens vencedores.", "Consolidar processos, aprendizados e responsabilidades do time.", "Apresentar roadmap do próximo trimestre com metas, testes e prioridades."], deliverableLabel: "ENTREGA DO MÊS", deliverable: "Relatório executivo, otimizações e roadmap do próximo trimestre" };
export const SLIDE_08 = { kicker: "CAPTAÇÃO | ATRATIVIDADE", title: "Como transformar um curso em uma escolha desejada", cards: [{ badge: "01 | ENTENDER O CANDIDATO", body: "Mapear motivações, objeções e critérios de escolha: carreira, mercado, experiência prática, reconhecimento, investimento e segurança.", meta: "Ouvir candidatos, alunos, Comercial e Coordenações antes de definir a promessa." }, { badge: "02 | DEFINIR A PROPOSTA DE VALOR", body: "Traduzir atributos acadêmicos em benefícios percebidos. O candidato precisa entender o que vai viver, aprender e construir a partir daquela formação.", meta: "Pergunta central: por que este curso merece entrar na minha lista de escolhas?" }, { badge: "03 | CRIAR UMA MENSAGEM POR PÚBLICO", body: "Adaptar a narrativa para diferentes momentos e perfis sem perder a identidade institucional. A campanha deve falar a linguagem do candidato e resolver uma dúvida real.", meta: "Uma promessa clara para cada público, não uma comunicação genérica." }, { badge: "04 | TRANSFORMAR INTERESSE EM AÇÃO", body: "Levar a mensagem para uma jornada simples: conteúdo ou anúncio, página ou WhatsApp, atendimento, inscrição e matrícula.", meta: "Marketing e Comercial precisam trabalhar a mesma promessa." }] satisfies BadgeCard[], note: "Não vender apenas uma graduação. Vender uma perspectiva de futuro que o candidato consiga enxergar." };
export const SLIDE_08B = { kicker: "CAPTAÇÃO | PROVA E CONVERSÃO", title: "Como fazer o candidato acreditar, desejar e decidir", cards: [{ badge: "01 | MOSTRAR, NÃO APENAS FALAR", body: "Transformar professores, alunos, projetos, desafios, eventos, ambientes e bastidores em evidências concretas da experiência que o candidato terá.", meta: "Prova social reduz a distância entre promessa e realidade." }, { badge: "02 | CONSTRUIR DESEJO", body: "Criar conteúdos que permitam ao jovem se imaginar naquele ambiente e naquela carreira. Mostrar pessoas reais, histórias, conquistas e possibilidades.", meta: "Descobrir, desejar, considerar, decidir." }, { badge: "03 | TRATAR OBJEÇÕES", body: "Mapear as principais dúvidas antes da matrícula e criar respostas claras para preço, carreira, diferenciais, rotina, empregabilidade e segurança da escolha.", meta: "Cada objeção vira conteúdo, argumento comercial ou melhoria de jornada." }, { badge: "04 | CONVERTER COM DISCIPLINA", body: "Registrar origem e etapa do lead, definir SLA de atendimento, criar follow up e recuperar quem demonstrou interesse mas não avançou.", meta: "O resultado não é o lead. É a matrícula com qualidade." }] satisfies BadgeCard[], note: "Diferencial operacional: transformar promessa em experiência, prova e conversão mensurável." };
export const SLIDE_09 = { kicker: "CAPTAÇÃO | MIX DE CANAIS", title: "Cada canal cumpre um papel no funil", cards: [{ badge: "Instagram", body: "Construir desejo, identificação e prova social", meta: "Reels, stories, alunos, professores, rotina e experiências" }, { badge: "TikTok", body: "Ganhar relevância junto ao público jovem", meta: "Conteúdo nativo, carreira, bastidores e linguagem da plataforma" }, { badge: "Google Ads", body: "Capturar intenção de quem já procura uma graduação", meta: "Busca por curso, região e termos de alta intenção" }, { badge: "Meta Ads", body: "Escalar descoberta e recuperar interesse", meta: "Prospecção, remarketing e testes de criativos e públicos" }, { badge: "Landing pages", body: "Transformar interesse em ação", meta: "Oferta clara, prova, CTA, formulário curto e rastreamento" }, { badge: "WhatsApp e CRM", body: "Transformar lead em oportunidade e matrícula", meta: "SLA, follow up, nutrição e recuperação de abandono" }] satisfies BadgeCard[], note: "Eventos, experiências no campus e parcerias entram como canais de confiança e consideração, com rastreamento da origem sempre que possível." };
export const SLIDE_10 = { kicker: "JORNADA DO CANDIDATO", title: "Menos atrito. Mais velocidade. Mais conversão.", sectionLabel: "O que muda em cada etapa", steps: [{ number: "01", title: "Descoberta", body: "Conteúdo e mídia levam o público certo para uma proposta de valor clara." }, { number: "02", title: "Lead", body: "Página ou formulário simples, origem registrada e próximo passo explícito." }, { number: "03", title: "Atendimento", body: "Lead quente recebe contato rápido, consultivo e contextualizado ao interesse." }, { number: "04", title: "Decisão", body: "Objeções são tratadas com prova social, diferenciais, conteúdo e follow up." }, { number: "05", title: "Matrícula", body: "Processo simples, recuperação de abandono e comunicação clara até a conclusão." }] satisfies JourneyStep[] };
export const SLIDE_11 = { kicker: "PESSOAS | CLIMA E ENGAJAMENTO", title: "Um time alinhado entrega melhor e mais rápido", cards: [{ badge: "COMUNICAÇÃO", body: "Daily curta, reunião semanal de prioridades e canal único para demandas.", meta: "Menos ruído, mais previsibilidade" }, { badge: "COLABORAÇÃO", body: "Brainstorm quinzenal e retrospectiva das campanhas com troca de aprendizados.", meta: "Ideias melhores, aprendizado compartilhado" }, { badge: "PERTENCIMENTO", body: "Conectar cada entrega ao propósito e aos resultados da jornada do aluno.", meta: "Mais participação, mais senso de dono" }, { badge: "RECONHECIMENTO", body: "Celebrar resultados, evolução, colaboração e boas iniciativas.", meta: "Feedback frequente, valorização" }, { badge: "CRIATIVIDADE", body: "Reservar espaço para testes de formatos, mensagens e experiências novas.", meta: "Experimentar, medir, aprender" }, { badge: "INTEGRAÇÃO", body: "Marketing, Comercial e Coordenações em rituais orientados ao mesmo funil.", meta: "Decisão mais rápida, jornada integrada" }] satisfies BadgeCard[] };
export const SLIDE_12 = { kicker: "GESTÃO POR DADOS", title: "KPIs que mostram onde agir, não apenas o que aconteceu", headers: { indicator: "Indicador", target: "Meta inicial", frequency: "Frequência" }, rows: [{ indicator: "Leads qualificados", target: "Definir após baseline", frequency: "Semanal" }, { indicator: "Inscrições", target: "Meta após baseline", frequency: "Semanal" }, { indicator: "Matrículas", target: "Meta após baseline", frequency: "Semanal" }, { indicator: "Conversão por etapa", target: "Melhorar vs. baseline", frequency: "Semanal" }, { indicator: "Custo por lead qualificado", target: "Otimizar vs. baseline", frequency: "Semanal" }, { indicator: "Custo por matrícula", target: "Otimizar vs. baseline", frequency: "Semanal" }, { indicator: "Abandono do funil", target: "Reduzir vs. baseline", frequency: "Quinzenal" }, { indicator: "Tempo de resposta", target: "Criar SLA e medir adesão", frequency: "Diário" }, { indicator: "Clima e satisfação", target: "Estabelecer baseline", frequency: "Mensal" }] satisfies KpiRow[], note: "Os percentuais não devem ser inventados antes do diagnóstico. Primeiro estabeleço o baseline real; depois defino metas desafiadoras e possíveis." };
export const SLIDE_13 = { kicker: "RESULTADOS ESPERADOS", title: "Ao final de 90 dias, o que deve estar diferente", items: ["Funil de captação visível, com origem, qualidade e conversão por etapa.", "Campanhas e mensagens prioritárias estruturadas por público e oferta.", "Mais previsibilidade de geração e tratamento de leads qualificados.", "Jornada com menos atritos, SLA de atendimento e recuperação de abandonos.", "Marketing e Comercial acompanhando os mesmos números e prioridades.", "Equipe com rituais de comunicação, colaboração, reconhecimento e aprendizado."] };
export const SLIDE_14 = { kicker: "DIFERENCIAIS DA MINHA PROPOSTA", title: "O que diferencia minha forma de atuar como Coordenador", cards: [{ number: "01", title: "Começo pelo diagnóstico: não aumento mídia antes de entender funil, oferta, público e gargalos." }, { number: "02", title: "Transformo curso em proposta de valor: conecto formação, experiência e carreira a uma razão clara para escolha." }, { number: "03", title: "Uno Marketing e Comercial: a promessa da campanha continua no atendimento até a matrícula." }, { number: "04", title: "Trabalho com experimentação: testes pequenos, leitura de dados e escala apenas do que comprovar resultado." }, { number: "05", title: "Lidero com clareza: prioridades visíveis, autonomia, feedback e reconhecimento." }, { number: "06", title: "Integro áreas: Marketing, Comercial e Coordenações participam da mesma visão da jornada do aluno." }] satisfies NumberedCard[], note: "Meu diferencial: unir estratégia, execução, dados e pessoas para transformar marketing em resultado sustentável." };
export const SLIDE_15: CoverContent = { badge: "SÍNTESE", title: "90 dias para criar tração", subtitle: "Diagnóstico, implementação, otimização", lines: ["Priorizar poucas alavancas de maior impacto.", "Criar uma rotina de gestão orientada por dados.", "Fazer Marketing e Comercial trabalharem sobre o mesmo funil.", "Construir uma equipe mais integrada, criativa e responsável pelos resultados."] };
export const SLIDE_16: CoverContent = { badge: "ENCERRAMENTO", title: "OBRIGADO!", subtitle: "Proposta de atuação", lines: ["Coordenador de Marketing iCEV", "Antonio Fontes", "comfontes@gmail.com", "(86) 99997 4164"] };
export const SLIDE_TITLES = ["Capa", "Visão Executiva", "Leitura do Desafio", "Diagnóstico Inicial", "Mês 1: Diagnóstico e Planejamento", "Mês 2: Implementação", "Mês 3: Otimização e Resultados", "Atratividade dos Cursos", "Prova e Conversão", "Mix de Canais", "Jornada do Candidato", "Clima e Engajamento", "Indicadores e KPIs", "Resultados Esperados", "Diferenciais da Minha Proposta", "Síntese dos 90 Dias", "Encerramento"] as const;
export const TOTAL_SLIDES = SLIDE_TITLES.length;
